version: '3.1'
services:
  metrics-db:
    image: influxdb
    hostname: pipeline-metrics-db
    ports:
      - ${METRICS_DB_PORT}:8086
    volumes:
      - influx_data:/var/lib/influxdb
      - influx_config:/etc/influxdb
    networks:
      - back_tier

  grafana:
    image: grafana/grafana
    hostname: pipeline-grafana
    ports:
      - ${GRAFANA_PORT}:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_NAME: "Janelia"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_config:/etc/grafana
      - grafana_log:/var/log/grafana
    networks:
      - back_tier

  message-queue:
    image: rabbitmq:3-management
    hostname: pipeline-message-queue
    ports:
      - ${MESSAGE_QUEUE_PORT}:5672
      - ${MESSAGE_QUEUE_API_PORT}:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "mqsecret"
    volumes:
      - mq_data:/var/lib/rabbitmq
    networks:
      - back_tier

  pipeline-db:
    image: postgres:9
    hostname: pipeline-db
    ports:
      - ${PIPELINE_DB_PORT}:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: "pgsecret"
    volumes:
      - pipeline_data:/var/lib/postgresql/data
      - ./datastore/pipeline:/docker-entrypoint-initdb.d
    networks:
      - back_tier

  pipeline-client:
    image: mouselightpipeline/pipeline-client
    hostname: pipeline-client
    environment:
      PIPELINE_API_HOST: ${PIPELINE_API_HOST}
      PIPELINE_API_PORT: ${PIPELINE_API_PORT}
    ports:
      - ${PIPELINE_CLIENT_PORT}:3100
    networks:
      - back_tier

  canopus-client:
    image: mouselightpipeline/worker-client
    hostname: canopus-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_CANOPUS_API_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_LOCAL_WORKER_API_PORT}
    ports:
      - ${PIPELINE_CANOPUS_LOCAL_CLIENT_PORT}:3600
    networks:
      - back_tier

  canopus-cluster-client:
    image: mouselightpipeline/worker-client
    hostname: canopus-cluster-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_CANOPUS_API_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_CLUSTER_WORKER_API_PORT}
    ports:
      - ${PIPELINE_CANOPUS_CLUSTER_CLIENT_PORT}:3600
    networks:
      - back_tier

  sirius-client:
    image: mouselightpipeline/worker-client
    hostname: sirius-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_SIRIUS_API_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_LOCAL_WORKER_API_PORT}
    ports:
      - ${PIPELINE_SIRIUS_LOCAL_CLIENT_PORT}:3600
    networks:
      - back_tier

  sirius-cluster-client:
    image: mouselightpipeline/worker-client
    hostname: sirius-cluster-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_SIRIUS_API_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_CLUSTER_WORKER_API_PORT}
    ports:
      - ${PIPELINE_SIRIUS_CLUSTER_CLIENT_PORT}:3600
    networks:
      - back_tier

  vega-client:
    image: mouselightpipeline/worker-client
    hostname: vega-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_VEGA_API_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_LOCAL_WORKER_API_PORT}
    ports:
      - ${PIPELINE_VEGA_LOCAL_CLIENT_PORT}:3600
    networks:
      - back_tier

  vega-cluster-client:
    image: mouselightpipeline/worker-client
    hostname: vega-cluster-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_VEGA_API_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_CLUSTER_WORKER_API_PORT}
    ports:
      - ${PIPELINE_VEGA_CLUSTER_CLIENT_PORT}:3600
    networks:
      - back_tier

volumes:
  influx_data:
  influx_config:
  grafana_config:
  grafana_log:
  grafana_data:
  mq_data:
  pipeline_data:

networks:
  back_tier:
