version: '3.1'
#
# There are a number of required environmental variables.  For a new installation, copy and past .env-template as .env
# and change the values as appropriate.
#
# This is configured for standard Janelia Mouse Light resources as an example.  It can be left unchanged if the number
# of workers will be same, unless you want to change the container host names for aesthetic reasons.  Otherwise workers
# can be added and removed in conjunction with env vars set in .env.
#
services:
  #
  # Not present: worker backend/api service - must be run where local paths to data are accessible
  #
  worker1-client:
    image: mouselightpipeline/worker-client:1.4
    hostname: canopus-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_WORKER1_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_WORKER_API_PORT}
      NODE_ENV: production
    ports:
      - ${PIPELINE_WORKER1_CLIENT_PORT}:6301
    volumes:
      - "${PIPELINE_LOG_PATH}:/var/log/pipeline"
    networks:
      - back_tier

  worker2-client:
    image: mouselightpipeline/worker-client:1.4
    hostname: sirius-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_WORKER2_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_WORKER_API_PORT}
      NODE_ENV: production
    ports:
      - ${PIPELINE_WORKER2_CLIENT_PORT}:6301
    volumes:
      - "${PIPELINE_LOG_PATH}:/var/log/pipeline"
    networks:
      - back_tier

  worker3-client:
    image: mouselightpipeline/worker-client:1.4
    hostname: vega-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_WORKER3_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_WORKER_API_PORT}
      NODE_ENV: production
    ports:
      - ${PIPELINE_WORKER3_CLIENT_PORT}:6301
    volumes:
      - "${PIPELINE_LOG_PATH}:/var/log/pipeline"
    networks:
      - back_tier

  worker4-client:
    image: mouselightpipeline/worker-client:1.4
    hostname: cluster-client
    environment:
      PIPELINE_WORKER_API_HOST: ${PIPELINE_WORKER4_HOST}
      PIPELINE_WORKER_API_PORT: ${PIPELINE_WORKER_API_PORT}
      NODE_ENV: production
    ports:
      - ${PIPELINE_WORKER4_CLIENT_PORT}:6301
    volumes:
      - "${PIPELINE_LOG_PATH}:/var/log/pipeline"
    networks:
      - back_tier

volumes:
  log_output:

networks:
  back_tier:
